Hass 32 Clustering
usdot-fhwa-stol/OpenPCDet pull request #3
Opened 2024-12-11 15:40 UTC by john-chrosniak

# PR Details
## Description

This PR adds a script that implements LiDAR clustering according to the DIN SAE Spec.

The steps of the algorithm include:

1. Initialize cluster centroids at the position of all LiDAR points in the measurement frame with the most points

2. Run K-means clustering using LiDAR points throughout all frames to refine the cluster centroids

3. Determine the maximum cluster radius given the current centroids (this is half the distance between the two closest centroids)

4. Find the point that is furthest from any given centroid. If it does not fall within the radius of the closest cluster, add a centroid at this point and re-run K-means to further refine the centroids. 

5. Repeat steps 3 and 4 until all points belong to a cluster.

## Related GitHub Issue

NA

## Related Jira Key

[HASS-32](https://usdot-carma.atlassian.net/browse/HASS-32)

## Motivation and Context

Clustering is needed to evaluate several KPIs of the DIN SAE Spec.

## How Has This Been Tested?

This was developed and tested using simulated LiDAR points that were artificially created by injecting random noise and dropout into evenly spaced out points. The intention was to mimic a noisy scan pattern.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2025-01-03 21:07 UTC, JonSmet requested changes

2025-01-03 21:07 UTC, JonSmet commented on din-sae-scripts/clustering.py
> +    kitti_rotation = R.from_euler("zyx", (0.0, 90.0, -90.0), degrees=True)
While this is currently hardcoded, could this come from the config files stored under "din-sae-scripts/config" in https://github.com/usdot-fhwa-stol/OpenPCDet/pull/4

2025-01-03 21:49 UTC, john-chrosniak commented on din-sae-scripts/clustering.py
> +    kitti_rotation = R.from_euler("zyx", (0.0, 90.0, -90.0), degrees=True)
This transformation converts the annotation from camera coordinates to LiDAR coordinates according to the KITTI format. I added a comment and link to a blog post detailing this transformation: https://towardsdatascience.com/kitti-coordinate-transformations-125094cd42fb

2025-01-06 15:35 UTC, JonSmet requested changes

2025-01-06 15:35 UTC, JonSmet commented on din-sae-scripts/clustering.py
> +    # Get the bounding box of the annotation target (Should be in the first annotation in the dataset)
Nit: Minor typo, I think this should be "engineering target annotated" (or similar)

2025-01-06 15:35 UTC, JonSmet commented on din-sae-scripts/clustering.py
> +import numpy as np
Looks good! Can we add a brief description of this file to the README (maybe after https://github.com/usdot-fhwa-stol/OpenPCDet/pull/4 is merged, if that makes more sense) for this script? Might make sense to include a link to the relevant Confluence page(s) in there as well.

2025-01-06 15:35 UTC, JonSmet commented on din-sae-scripts/clustering.py
> +def load_lidar_data(dataset_path, frame_limit=np.inf):
I think eventually we will have multiple annotated engineering targets for each dataset, so that we can see how different DIN SAE Spec KPIs are affected as a function of distance. We will likely need to update the script to support multiple annotated engineering targets in the future. Not something we need to update now, but just wanted to highlight this.

2025-01-08 15:08 UTC, john-chrosniak commented on din-sae-scripts/clustering.py
> +    # Get the bounding box of the annotation target (Should be in the first annotation in the dataset)
Fixed!

2025-01-08 15:11 UTC, john-chrosniak commented on din-sae-scripts/clustering.py
> +def load_lidar_data(dataset_path, frame_limit=np.inf):
Yes totally agree with you, I made sure to highlight in the documentation that the script will currently just use the first annotated engineering target.

2025-01-08 15:42 UTC, JonSmet approved these changes

2025-01-08 15:44 UTC, merged