Hass 31 cvat integration
usdot-fhwa-stol/OpenPCDet pull request #4
Opened 2024-12-23 17:10 UTC by john-chrosniak

# PR Details
## Description

This PR adds a script that converts annotations from the CVAT platform to the KITTI dataset format, which is used for training and testing in OpenPCDet.

## Related GitHub Issue

NA

## Related Jira Key

[HASS-31](https://usdot-carma.atlassian.net/browse/HASS-31)

## Motivation and Context

Converting annotations to the KITTI format is needed to leverage the training and evaluation scripts of the OpenPCDet platform, and is also a prerequisite for running the clustering algorithm developed in #3 .

## How Has This Been Tested?

Each LiDAR dataset was convert to the KITTI format and visualized using [this KITTI visualization tool](https://github.com/kuixu/kitti_object_vis) to confirm that the point clouds and annotations were correctly transformed. The clustering algorithm was also tested on each of the datasets to further confirm.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2025-01-03 20:08 UTC, JonSmet requested changes

2025-01-03 20:08 UTC, JonSmet commented on din-sae-scripts/cvat_to_openpcdet.py
> +def cvat_to_openpcdet(pcd_path, json_path, params_path, dataset_root):
In the end, 'dataset_root' is created with multiple subdirectories (velodyne, label_2, image_2, calib). Does the 'dataset_root' directory as a whole satisfy the KITTI dataset format, or are only some of these subdirectories needed? If only some are needed, could a brief description be provided at the top of this function with an explanation of the structure and contents of the final created dataset_root directory?

2025-01-03 21:31 UTC, john-chrosniak commented on din-sae-scripts/cvat_to_openpcdet.py
> +
Added!

2025-01-03 21:31 UTC, john-chrosniak commented on din-sae-scripts/cvat_to_openpcdet.py
> +import json
Yes these should all be captured in `environment.yaml`

2025-01-03 21:33 UTC, john-chrosniak commented on din-sae-scripts/cvat_to_openpcdet.py
> +    if not (os.path.isdir(os.path.join(dataset_root, "velodyne"))):
Yeah this is  a directory used in the structure of the KITTI dataset. I added details on this in the README

2025-01-03 21:33 UTC, john-chrosniak commented on din-sae-scripts/cvat_to_openpcdet.py
> +    ## Make bin_path directory
Fixed!

2025-01-03 21:34 UTC, john-chrosniak commented on din-sae-scripts/cvat_to_openpcdet.py
> +def cvat_to_openpcdet(pcd_path, json_path, params_path, dataset_root):
The `dataset_root` is the base directory to create the KITTI dataset in, which includes `velodyne`, `label_2`, `image_2`, and `calib`. Details on this are now in the README.

2025-01-06 14:53 UTC, JonSmet approved these changes

2025-01-08 14:23 UTC, merged